### ISSUE TITLE
Figure out why low ell lensing Cls don't match CCL

### ISSUE THREAD

**Issue by EiffL** [DifferentiableUniverseInitiative/jax_cosmo#15]
Below \ell of 100 or so, the lensing angular  power spectrum seems to disagree  with CCL, despite using the same Limber approximation in both  implementation, althgough jax_cosmo performs the integrals slightly differently. 
Here is an illustration of the problem:
![image](https://user-images.githubusercontent.com/861591/81226679-833b2780-8feb-11ea-8062-90ad3efd159f.png)
thoughts and ideas as to why this might happen are welcome!

**Comment by jmsull** [comment]
<img width="1143" alt="limber_jax" src="https://user-images.githubusercontent.com/50674574/81267949-2005c100-8ffc-11ea-967d-509ce5bf15ca.png">

Seems to almost match up by multiplying by (ell/(ell+.5))**2 ?

I don't really have anything else useful to say, but from looking at the eqn 78 in the [paper](https://arxiv.org/pdf/1812.05995.pdf), since you integrate in scale factor whereas they integrate in k - maybe this is related to the difference in integrals you mentioned?

**Comment by EiffL** [comment]
ah! ok that's useful :-D Thanks so much! I've been trying various ell factors but couldn't find one that fit ^^'
Yes, I've rewritten the integral in `a` instead of `k`  I'm pretty sure I missed a conversion factor somewhere.

**Comment by EiffL** [comment]
Found what the problem was >.< equations were correct, but CCL was messing up because I wasn't using enough points to sample the n(z), with much more nz samples, CCL converges to jax-cosmo \o/ So it's solved, thanks @jmsull for looking into it :-D
